### ISSUE TITLE
Testing Documentation Needed

### ISSUE THREAD

**Issue by huangs1** [Tada-Project/tada#6]
In gatorgrader, there was outputs of running the testing and proving the coverage/covered files. 

Sample documentation from running ```pipenv run pytest```

```
tests/test_arguments.py ......................                           [ 55%]
tests/test_configuration.py .............                                [ 87%]
tests/test_generate.py ...                                               [ 95%]
tests/test_run.py ..                                                     [100%]

```

**Comment by lussierc** [comment]
@huangs1 I think this would be a good thing to add to the repository's documentation. It would give user's a good idea of how the test cases function and what the output of this testing functions. 

This would be fairly easy to add to the README. I agree that we could just take the output from running `pipenv run pytest`.
