### ISSUE TITLE
Feature Idea: Comparison Feature

### ISSUE THREAD

**Issue by lussierc** [Tada-Project/tada#8]
If properly implemented, this feature could be used to quickly compare different big-og-notation outputs from testing algorithms in the program. A #7 save feature could be used to save outputs. A load feature could be implemented to open these previously saved files to use in the comparison.

**Comment by Lancasterwu** [comment]
I think this is a great idea. However, we need to wait until we finish the time calculation feature.

**Comment by lussierc** [comment]
This issue was incorrectly closed by @huangs1. Sorry for the inconvenience.

**Comment by huangs1** [comment]
@lussierc Sorry for the inconvience, I was so fascinated by the idea I randomly clicked close comment.

**Comment by Lancasterwu** [comment]
Implemented with #78
