### ISSUE TITLE
Refactor the Display Module to Make it More Testable

### ISSUE THREAD

**Issue by gkapfham** [Tada-Project/tada#85]
The current implementation of the `display` module has multiple functions that
directly create output to the console. An alternative implementation approach
would be for these functions to return a value instead of (or in addition to)
printing to the console. This would make it easier to write test cases for these
functions. Finally, we should write test cases for all of these functions so as
to increase the code coverage of this module.

**Comment by enpuyou** [comment]
Close this issue since #88 has been merged
